[package]
name = "db-diff"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["shell-open"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
