services:
  mysql80:
    container_name: table-snapshot-mysql80
    build: ./docker/mysql80
    ports:
      - 19000:3306
    volumes:
      - ./docker/mysql80/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: table-snapshot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
