services:
  testdata-mysql80:
    build: ./docker/testdata-mysql80
    ports:
      - 19001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdata
      MYSQL_USER: user
      MYSQL_PASSWORD: password
